### PR TITLE
fix acceptance tests for mono

### PR DESCRIPTION
**Pull request by adamralph**
connects to #151

superset of #211

### CODE REVIEW

**Comment by eatdrinksleepcode** [comment]
LGTM. TravisCI seems to be failing b/c it can't find scriptcs?

**Comment by adamralph** [comment]
Yeah, that's the problem with TravisCI. It can't find scriptcs. In TeamCity, we set the SCRIPTCS_PATH env var and that is what the acceptance tests use to locate it. I tried to set the SCRIPTCS_PATH env var in the latest `.travis.yml` change but the relative path is wrong. Perhaps this just needs to be expanded to the absolute path somehow.

**Comment by adamralph** [comment]
OK, the acceptance tests are now running on Travis, but there seem to be some genuine failures.

**Comment by adamralph** [comment]
There seems to be three flavours of failures
- `DisplayingTasks.*` - these are all because of Windows vs *nix line endings in the assertions. These should be easy enough to fix.
- `Plugins.Exec.*` - for some reason `mono` is returning an exit code of 2. I suspect this may be due to incorrect paths, but I'm not sure.
- `ScriptExecution.CompilationFails` - I suspect this is because of https://github.com/scriptcs/scriptcs/issues/1054

**Comment by adamralph** [comment]
I've fixed the `DisplayingTasks.*` tests.

**Comment by adamralph** [comment]
I've skipped `ScriptExecution.CompilationFails` for now. This is indeed falling fowl of scriptcs/scriptcs#1054.

That only leaves the `Plugins.Exec.*` tests. I think the best thing to do is to simplify these by removing the `Bau.Test.Acceptance.CreateFile` project and switching between executing a cmd file and a bash script, depending on OS. The OS can be determined by checking the environment variable `OS`. In Windows this is set to `Windows_NT`. In *nix it is either unset or is something else.

**Comment by eatdrinksleepcode** [comment]
Sorry, I should have fixed all of these when I rebased.

Agreed that removing the CreateFile project would simplify the acceptance tests. Anything I can do to help?

**Comment by adamralph** [comment]
Branch pushed to https://github.com/bau-build/bau/tree/151

**Pull request closed without merging**
