### PR TITLE
green: fixes for some strange acceptance test behavior

### LINKED ISSUE #198: Acceptance tests cannot be run with scriptcs 0.14.1
What is the current state of the acceptance tests? I am unable to get them to run successfully.
1. The path to the output folder as defined in Bau.Test.Acceptance/Support/Baufile.cs line 33-39 does not exist. To workaround this I replaced the entire `#if DEBUG with`Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)`.
2. In the Run method in the same file, the FileName to run is set to "scriptcs". Windows complains that it can't find this file, since it is actually called "scriptcs.bat". Changing the FileName to "scriptcs.bat" allowed me to continue.
3. Now, for all tests, scriptcs always returns an exit code of -1, causing the tests to fail, even though running scriptcs from the command line seems to succeed.

Any ideas? Is anyone running the acceptance tests on a regular basis?

### PR DESCRIPTION
**Pull request by aarondandy**
Closes #198

This seems to give me more stable & reliable results when running the acceptance tests.

Hey @eatdrinksleepcode, let us know if this works for you.

### CODE REVIEW

**Comment by aarondandy** [comment]
Travis CI fails because of some strange path in the tests:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/travis/build/bau-build/bau/src/test/Bau.Test.Component/bin/Release/src/test/Bau.Test.Component/bin/Release/Bau.Test.Component.dll.TestResults.xml".
```

I don't know what is wrong with TeamCity but it looks like it may be using a version of scriptcs that is out of date and looks in `bin` instead of `scriptcs_bin`. It would probably need to be 0.14.1 for this to work.

```
[00:52:29][Step 2/4] Starting: C:\Windows\system32\config\systemprofile\.svm\bin\svm.cmd install 0.13.3
```

**Comment by adamralph** [comment]
I've fixed the TeamCity build to use scripcs 0.14.1

TravisCI is just an intermittent fault. I'll re-run it until it passes.

**Comment by adamralph** [comment]
TeamCity still not fixed. I'm working on it...

**Comment by adamralph** [comment]
Thanks @aarondandy !

I had to add another commit to add support for using a `SCRIPTCS_PATH` env var to locate scriptcs during acceptance test execution. This is to allow the TeamCity build to use the version of scriptcs that is installed during the build using svm when executing the tests.

**Comment by aarondandy** [comment]
:+1: Most of my other changes are to support NCrunch for development of the list feature and other things in the future.

**Pull request merged**
