### PR TITLE
Adjust comments in gruntfile to show build steps

### PR DESCRIPTION
**Pull request by hyrmn**
The grunt file was pointing at the .sln with the correct relative path. However, it wasn't correctly resolving the packages directory.

The readme at the top of the file didn't specify copying the gruntfile anywhere and so it seemed ok to run it from the comparison directory directly. This works with the change to the packages path.

Also normalized the quotes around strings.

### CODE REVIEW

**Comment by adamralph** [comment]
Thanks!

The thing is, there is a local `packages.config` in `/comparison`. If you run `scriptcs -install` once then `/comparison/packages` is created and populated with the required files. This is why it is stated at the top of the grunfile that you should build with Bau once before building with grunt.

If you do this and add a line to log the path which is being used for, e.g. the nuget command, then you can see it using the exe under `/comparison/packages`.

**Comment by adamralph** [comment]
Perhaps the comment  should state explicitly that you should with build with Bau once _using baufile.csx which is next to this file_ to make it clearer.

I don't want that people have to build the entire solution after cloning before running one of the comparison scripts. It should be enough to just run the cut down `/comparison/baufile.csx`. Or indeed, just run `scriptcs -install` in that folder.

**Comment by hyrmn** [comment]
@adamralph I think adding that will help, yes. I saw that it said to build Bau before using the other build runners so I went to the root dir and ran the build file there.

**Comment by adamralph** [comment]
Ah, I see. Sorry for the confusion. :blush:

If you still feel motivated, you could revert the path change, keep your quote normalisation, alter the comments, amend the commit and force push. Interested? The comment in `rakefile.rb` and possibly the one in `baufile.csx` would also need changing.

**Comment by hyrmn** [comment]
@adamralph Done. I think. for the gruntfile. If the changes look ok, I'll add them to the rakefile too.

**Comment by adamralph** [comment]
:ok_hand: spot on, thanks!

**Comment by adamralph** [comment]
relates to #81

**Pull request merged**
