### PR TITLE
Split ColorConsole out to separate project

### PR DESCRIPTION
**Pull request by davetimmins**
This moves the `ColorConsole` stuff into a separate project. I left the usage within `Bau` the same with the exception of changing `WriteLine(null)` to just `WriteLine()`. 

There is also the option to call it as below

``` csharp
ColorConsole.WriteLine(
    "Press".Colored(ConsoleColor.Gray),
    " Esc ".Colored(ConsoleColor.Red),
    "to exit".Colored(ConsoleColor.Gray));
```

### CODE REVIEW

**Comment by adamralph** [comment]
Awesome! Thanks very much. I'll review it ASAP. I'm on the road right now
with a phone only so I'm afraid it will have to wait until next week. This
is a great step towards spinning this off as a separate nupkg.

**Comment by davetimmins** [comment]
No problem. Yea would be great as a package, been using it for a recent project as there's nothing else as nice / easy to use from what I could see.

**Comment by davetimmins** [comment]
Also noticed that if you do something like

``` csharp
ColorConsole.WriteLine(
    "Press",
    " Esc ".Colored(ConsoleColor.Red),
    "to exit");
```

at the moment it will use the last set colour, so "Esc to exit", would all be red. Changing the implicit string operator for ColorToken to use the default colour of white can resolve this

``` csharp
public static implicit operator ColourToken(string text)
{
    return new ColourToken(text, ConsoleColor.White);
}
```

**Comment by adamralph** [comment]
Thanks for hanging in there. I'm afraid I still can't get onto this for a while, but the behaviour you mention surprises me. I thought I designed it so that the current colour is reverted after the rendering of each token but I guess I may be mistaken.

**Comment by davetimmins** [comment]
Ah you're right, must've been imagining things sorry :sob:

**Comment by adamralph** [comment]
@davetimmins sorry there's been no movement on this for a while.

I had a think about it and I decided that I didn't really want the project sitting as a separate DLL in Bau, but your change inspired me to go the whole hog and spin it off as a separate repo and package. See https://github.com/colored-console/colored-console and https://www.nuget.org/packages/ColoredConsole/.

The new repo is based on the current dev branch in Bau, so it doesn't contain the API enhancements you made, i.e. the `WriteLine` overloads and the `string` extension method. If you'd like to raise a PR over at the colored-console project I'd be more than happy to accept them there.

Furthermore, given your interest, would you like to join me in co-managing the colored-console repo as a committer?

**Comment by davetimmins** [comment]
That's great and good timing as I am about to use it again. I'll make the changes over there and submit a new PR.

Yes I'd be happy to co-manage the colored-console repository.

**Comment by adamralph** [comment]
Great! I've invited you to become an owner of the colored-console org. I'll take a look at your PR there ASAP.

**Pull request closed without merging**
